/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>
using namespace std;

int main()
{
	int answer = 0;
	int fibonacci1 = 1;
	int fibonacci2 = 1;
	int temp = 0;
	int limit = 4000000;
	do{
		if(fibonacci1 % 2 == 0)
			answer += fibonacci1;
		temp = fibonacci1;
		fibonacci1 += fibonacci2;
		fibonacci2 = temp;
	}while(fibonacci1 < limit);
	cout << answer << endl;
	return 0;
}
